### ISSUE TITLE
Submit button on form page to launch and populate Twitter input in new tab

### ISSUE THREAD

**Issue by djado** [citizendigital/startingpoint#46]

**Comment by djado** [comment]
Build your link to look something like this:

```
<a href="https://twitter.com/intent/tweet?text=hello+world&hashtags=world+peace" target="_blank">Submit</a>
```

**Comment by ccruz07** [comment]
been researching this, but so far I only see the info from Twitter can be sent back to website. so IDK

**Comment by djado** [comment]
I'll take this one. It overlaps with another task I'm working on.

**Comment by ccruz07** [comment]
Ok cool

**Comment by ccruz07** [comment]
I got the twitter button to work, just have not pushed up the updates. will send it now

**Comment by djado** [comment]
Done!
